export type Station = {
    name: string;
    latitude: number;
    longitude: number;
    line: 'LRT1' | 'LRT2' | 'MRT3';
    image: any;
  };
  
  export type StationMap = {
    [key in 'LRT1' | 'LRT2' | 'MRT3']: Station[];
  };
  
  export const stations: StationMap = {
    LRT1: [
        {
          name: 'Fernando Poe Jr. Station',
          latitude: 14.638056,
          longitude: 121.003333,
          line: 'LRT1',
          image: require('../../assets/images/LRT1/FPJ.jpg'),
        },
        {
          name: 'Balintawak Station',
          latitude: 14.6575,
          longitude: 121.003889,
          line: 'LRT1',
          image: require('../../assets/images/LRT1/Balintawak.jpg'),
        },
        {
          name: 'Monumento Station',
          latitude: 14.656944,
          longitude: 120.998611,
          line: 'LRT1',
          image: require('../../assets/images/LRT1/YAMAHA_Monumento.jpg'),
        },
        {
          name: '5th Avenue Station',
          latitude: 14.645833,
          longitude: 120.996667,
          line: 'LRT1',
          image: require('../../assets/images/LRT1/5thAve.jpeg'),
        },
        {
          name: 'R. Papa Station',
          latitude: 14.637222,
          longitude: 120.995278,
          line: 'LRT1',
          image: require('../../assets/images/LRT1/R_Papa.jpg'),
        },
        {
          name: 'Abad Santos Station',
          latitude: 14.630833,
          longitude: 120.994722,
          line: 'LRT1',
          image: require('../../assets/images/LRT1/Abad_Santos.jpg'),
        },
        {
          name: 'Blumentritt Station',
          latitude: 14.623056,
          longitude: 120.991944,
          line: 'LRT1',
          image: require('../../assets/images/LRT1/Blumentritt.jpg'),
        },
        {
          name: 'Tayuman Station',
          latitude: 14.616667,
          longitude: 120.988889,
          line: 'LRT1',
          image: require('../../assets/images/LRT1/Tayuman.jpg'),
        },
        {
          name: 'Bambang Station',
          latitude: 14.610833,
          longitude: 120.9875,
          line: 'LRT1',
          image: require('../../assets/images/LRT1/Bambang.jpg'),
        },
        {
          name: 'Doroteo Jose Station',
          latitude: 14.606111,
          longitude: 120.984444,
          line: 'LRT1',
          image: require('../../assets/images/LRT1/Doroteo_Jose.jpg'),
        },
        {
          name: 'Carriedo Station',
          latitude: 14.599722,
          longitude: 120.983611,
          line: 'LRT1',
          image: require('../../assets/images/LRT1/Carriedo.jpg'),
        },
        {
          name: 'Central Terminal Station',
          latitude: 14.594722,
          longitude: 120.983056,
          line: 'LRT1',
          image: require('../../assets/images/LRT1/Central.jpg'),
        },
        {
          name: 'United Nations Station',
          latitude: 14.582222,
          longitude: 120.984722,
          line: 'LRT1',
          image: require('../../assets/images/LRT1/United_Nations.jpg'),
        },
        {
          name: 'Pedro Gil Station',
          latitude: 14.573333,
          longitude: 120.986111,
          line: 'LRT1',
          image: require('../../assets/images/LRT1/Pedro_Gil.jpg'),
        },
        {
          name: 'Quirino Avenue Station',
          latitude: 14.5675,
          longitude: 120.988056,
          line: 'LRT1',
          image: require('../../assets/images/LRT1/Quirino.jpg'),
        },
        {
          name: 'Vito Cruz Station',
          latitude: 14.558056,
          longitude: 120.9925,
          line: 'LRT1',
          image: require('../../assets/images/LRT1/Vito_Cruz.jpeg'),
        },
        {
          name: 'Gil Puyat Station',
          latitude: 14.550556,
          longitude: 120.994722,
          line: 'LRT1',
          image: require('../../assets/images/LRT1/Gil_Puyat.jpeg'),
        },
        {
          name: 'Libertad Station',
          latitude: 14.543056,
          longitude: 120.996389,
          line: 'LRT1',
          image: require('../../assets/images/LRT1/Libertad.jpg'),
        },
        {
          name: 'EDSA Station',
          latitude: 14.5375,
          longitude: 120.997222,
          line: 'LRT1',
          image: require('../../assets/images/LRT1/EDSA.jpg'),
        },
        {
          name: 'Baclaran Station',
          latitude: 14.534444,
          longitude: 120.998333,
          line: 'LRT1',
          image: require('../../assets/images/LRT1/Baclaran.jpg'),
        },
      ],
  
    LRT2: [
        {
          name: 'Antipolo Station',
          latitude: 14.624722,
          longitude: 121.121111,
          line: 'LRT2',
          image: require('../../assets/images/LRT2/Antipolo.jpg'),
        },
        {
          name: 'Marikina-Pasig Station',
          latitude: 14.620278,
          longitude: 121.100278,
          line: 'LRT2',
          image: require('../../assets/images/LRT2/Marikina_Pasig.jpg'),
        },
        {
          name: 'Santolan Station',
          latitude: 14.622139,
          longitude: 121.085917,
          line: 'LRT2',
          image: require('../../assets/images/LRT2/Santolan_LRT.jpg'),
        },
        {
          name: 'Katipunan Station',
          latitude: 14.631097,
          longitude: 121.072958,
          line: 'LRT2',
          image: require('../../assets/images/LRT2/Katipunan.jpg'),
        },
        {
          name: 'Anonas Station',
          latitude: 14.628,
          longitude: 121.064694,
          line: 'LRT2',
          image: require('../../assets/images/LRT2/Anonas.jpg'),
        },
        {
          name: 'Araneta Center-Cubao Station',
          latitude: 14.622678,
          longitude: 121.052636,
          line: 'LRT2',
          image: require('../../assets/images/LRT2/Cubao_LRT.jpg'),
        },
        {
          name: 'Betty Go-Belmonte Station',
          latitude: 14.618333,
          longitude: 121.0425,
          line: 'LRT2',
          image: require('../../assets/images/LRT2/Betty_Go_Belmonte.jpg'),
        },
        {
          name: 'Gilmore Station',
          latitude: 14.613333,
          longitude: 121.033889,
          line: 'LRT2',
          image: require('../../assets/images/LRT2/Gilmore.jpg'),
        },
        {
          name: 'J. Ruiz Station',
          latitude: 14.610556,
          longitude: 121.026111,
          line: 'LRT2',
          image: require('../../assets/images/LRT2/J._Ruiz.jpg'),
        },
        {
          name: 'V. Mapa Station',
          latitude: 14.607778,
          longitude: 121.021389,
          line: 'LRT2',
          image: require('../../assets/images/LRT2/V._Mapa.jpg'),
        },
        {
          name: 'Pureza Station',
          latitude: 14.604167,
          longitude: 121.008056,
          line: 'LRT2',
          image: require('../../assets/images/LRT2/Pureza.jpg'),
        },
        {
          name: 'Legarda Station',
          latitude: 14.604444,
          longitude: 120.997222,
          line: 'LRT2',
          image: require('../../assets/images/LRT2/Legarda.jpg'),
        },
        {
          name: 'Recto Station',
          latitude: 14.603333,
          longitude: 120.983889,
          line: 'LRT2',
          image: require('../../assets/images/LRT2/Recto.jpg'),
        },
      ],
    
      MRT3: [
        {
          name: 'North Avenue Station',
          latitude: 14.654911,
          longitude: 121.031029,
          line: 'MRT3',
          image: require('../../assets/images/MRT3/North_Ave.jpg'),
        },
        {
          name: 'Quezon Avenue Station',
          latitude: 14.646551,
          longitude: 121.036266,
          line: 'MRT3',
          image: require('../../assets/images/MRT3/Quezon_Ave.jpg'),
        },
        {
          name: 'GMA-Kamuning Station',
          latitude: 14.637021,
          longitude: 121.042394,
          line: 'MRT3',
          image: require('../../assets/images/MRT3/GMA_Kamuning.jpg'),
        },
        {
          name: 'Araneta Center-Cubao Station',
          latitude: 14.621446,
          longitude: 121.053704,
          line: 'MRT3',
          image: require('../../assets/images/MRT3/Cubao_MRT.jpg'),
        },
        {
          name: 'Santolan-Annapolis Station',
          latitude: 14.607762,
          longitude: 121.056342,
          line: 'MRT3',
          image: require('../../assets/images/MRT3/Santolan_MRT.jpg'),
        },
        {
          name: 'Ortigas Station',
          latitude: 14.586, 
          longitude: 121.0564,
          line: 'MRT3',
          image: require('../../assets/images/MRT3/Ortigas.jpg'),
        },
        {
          name: 'Shaw Boulevard Station',
          latitude: 14.582151,
          longitude: 121.053689,
          line: 'MRT3',
          image: require('../../assets/images/MRT3/Shaw_Blvd.jpg'),
        },
        {
          name: 'Boni Station',
          latitude: 14.577235,
          longitude: 121.046125,
          line: 'MRT3',
          image: require('../../assets/images/MRT3/Boni.jpg'),
        },
        {
          name: 'Guadalupe Station',
          latitude: 14.566082,
          longitude: 121.045744,
          line: 'MRT3',
          image: require('../../assets/images/MRT3/Guadalupe.jpg'),
        },
        {
          name: 'Buendia Station',
          latitude: 14.554937,
          longitude: 121.034706,
          line: 'MRT3',
          image: require('../../assets/images/MRT3/Buendia.jpg'),
        },
        {
          name: 'Ayala Station',
          latitude: 14.550107,
          longitude: 121.028469,
          line: 'MRT3',
          image: require('../../assets/images/MRT3/Ayala.jpg'),
        },
        {
          name: 'Magallanes Station',
          latitude: 14.541006,
          longitude: 121.017759,
          line: 'MRT3',
          image: require('../../assets/images/MRT3/Magallanes.jpg'),
        },
        {
          name: 'Taft Avenue Station',
          latitude: 14.536972,
          longitude: 121.001709,
          line: 'MRT3',
          image: require('../../assets/images/MRT3/Taft_Ave.jpg'),
        },
      ]
    };